" https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/main/vim/vimrc :

set nocompatible      " Use Vim defaults (much better!)
set ai                " Always set auto-indenting on
set history=50        " keep 50 lines of command history
set ruler             " Show the cursor position all the time

" When doing tab completion, give the following files lower priority.
set suffixes+=.info,.aux,.log,.dvi,.bbl,.out,.o,.lo

set nomodeline
syntax on

if filereadable("/etc/vim/vimrc.local")
	source /etc/vim/vimrc.local
endif

" https://github.com/amix/vimrc/blob/master/vimrcs/basic.vim :

set ignorecase        " search
set smartcase         "  `-unless uppercase
set hlsearch
set incsearch
set magic             " search regex
set showmatch         " hilight matching bracket

" https://github.com/9001/lxc :

:nnoremap <F8> :setl noai nocin nosi inde=<CR>
set ts=4
set sw=4
set nu rnu

" smart home
noremap <expr> <silent> <Home> col('.') == match(getline('.'),'\S')+1 ? '0' : '^'
imap <silent> <Home> <C-O><Home>
